"""
Django settings for socialmedia project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-x4n5uj&qkfkw-=&_n0lx6u-yz1a8f_^$mhaz($vn5-55$9st4s")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [host.strip() for host in os.environ.get("ALLOWED_HOSTS", "*").split(",") if host.strip()]

# When importing production settings, defer security enforcement until production overrides load.
is_production_settings = os.environ.get("DJANGO_SETTINGS_MODULE", "").endswith("settings_production")
if not DEBUG and not is_production_settings:
    if SECRET_KEY.startswith("django-insecure-"):
        raise ImproperlyConfigured("Set a strong SECRET_KEY when DEBUG=False.")
    if "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured("Set explicit ALLOWED_HOSTS when DEBUG=False.")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom Apps
    "users.apps.UsersConfig",
    "posts.apps.PostsConfig",
]

# Cloudinary Integration for Production Media
if os.environ.get("CLOUDINARY_URL"):
    INSTALLED_APPS.append("cloudinary")
    INSTALLED_APPS.append("cloudinary_storage")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # Production Static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "users.middleware.EmailVerificationMiddleware",
    "users.middleware.APIRateLimitMiddleware",
]

ROOT_URLCONF = "socialmedia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.global_sidebar_context",
            ],
        },
    },
]

WSGI_APPLICATION = "socialmedia.wsgi.application"
ASGI_APPLICATION = "socialmedia.asgi.application"

# Django Channels Configuration
REDIS_URL = os.environ.get("REDIS_URL")
CHANNEL_LAYERS_AVAILABLE = False

if REDIS_URL:
    try:
        import channels_redis
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [{
                        "address": REDIS_URL,
                        "health_check_interval": 20,
                        "socket_keepalive": True,
                        "socket_timeout": 20,
                        "socket_connect_timeout": 5,
                        "retry_on_timeout": True,
                    }],
                },
            },
        }
        CHANNEL_LAYERS_AVAILABLE = True
    except ImportError:
        print("WARNING: channels_redis not installed. Using in-memory channel layer.")
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer"
            }
        }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL Database Configuration (Render + Neon)
# For local development, falls back to SQLite


def clean_database_url_for_django(database_url):
    """Remove Postgres runtime settings that are not valid DSN parameters."""
    if not database_url:
        return database_url

    split_url = urlsplit(database_url)
    blocked_params = {
        "statement_timeout",
        "idle_in_transaction_session_timeout",
        "lock_timeout",
    }
    query_params = [
        (key, value)
        for key, value in parse_qsl(split_url.query, keep_blank_values=True)
        if key not in blocked_params
    ]
    return urlunsplit(split_url._replace(query=urlencode(query_params)))


def database_url_requires_ssl(database_url):
    """Require SSL unless the database is explicitly local and local SSL is disabled."""
    if not database_url:
        return True
    split_url = urlsplit(database_url)
    query_params = dict(parse_qsl(split_url.query, keep_blank_values=True))
    sslmode = query_params.get("sslmode", "").lower()

    if sslmode in {"disable", "allow", "prefer"}:
        return False

    local_hosts = {"localhost", "127.0.0.1", "::1"}
    if split_url.hostname in local_hosts and os.environ.get("DB_ALLOW_LOCAL_DB_NO_SSL", "False").lower() in {"1", "true", "yes"}:
        return False

    return os.environ.get("DB_ENFORCE_SSL", "True").lower() in {"1", "true", "yes"}


def database_uses_neon_pooler(database_config):
    """Detect Neon pooled connections, which reject some startup parameters."""
    host = database_config.get("HOST", "")
    return "neon.tech" in host and "-pooler" in host


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "aetheria"),
        "USER": os.environ.get("DB_USER", "aetheria"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 10,
        }
    }
}

# Override with DATABASE_URL if provided (Render environment with Neon PostgreSQL)
if os.environ.get("DATABASE_URL"):
    try:
        import dj_database_url
        
        # Parse database URL from environment
        db_url = clean_database_url_for_django(os.environ.get("DATABASE_URL"))
        
        # Configure database with dj_database_url
        # dj_database_url automatically handles SSL parameters from the URL
        DATABASES["default"] = dj_database_url.config(
            default=db_url,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=database_url_requires_ssl(db_url),
        )
        
        # Preserve Neon-specific SSL and channel binding parameters
        # These are automatically parsed by dj_database_url from the connection string
        if "OPTIONS" not in DATABASES["default"]:
            DATABASES["default"]["OPTIONS"] = {}
        
        # Add connection timeout (Neon-specific)
        DATABASES["default"]["OPTIONS"].update({
            "connect_timeout": 10,
            "keepalives": 1,
            "keepalives_idle": 30,
        })
        DATABASES["default"]["OPTIONS"].setdefault(
            "sslmode",
            "require" if database_url_requires_ssl(db_url) else "prefer"
        )
        
        print("Using DATABASE_URL for Neon PostgreSQL (Render production)")
        print(f"Database: {DATABASES['default'].get('NAME', 'unknown')}")
        
    except Exception as e:
        print(f"Error configuring database from URL: {e}")
        print("Falling back to default PostgreSQL configuration")
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "aetheria"),
            "USER": os.environ.get("DB_USER", "aetheria"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "CONN_MAX_AGE": 600,
            "OPTIONS": {
                "connect_timeout": 10,
            }
        }

# Fall back to SQLite only if both DATABASE_URL and DB_HOST are missing (local development)
if not os.environ.get("DATABASE_URL") and os.environ.get("DB_HOST", "localhost") == "localhost":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    print("Using SQLite (development mode)")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Static files storage settings for WhiteNoise caching/compression (modern Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Media Files (User uploads)
MEDIA_URL = "/media/"

if os.environ.get("CLOUDINARY_URL"):
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"
    MEDIA_ROOT = BASE_DIR / "media"
else:
    MEDIA_ROOT = BASE_DIR / "media"

# Authentication Redirects
LOGIN_REDIRECT_URL = "feed"
LOGOUT_REDIRECT_URL = "landing"
LOGIN_URL = "login"


# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF Protection
CSRF_COOKIE_HTTPONLY = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'  # Lax for better cross-site compatibility
CSRF_COOKIE_AGE = 31449600  # One year
CSRF_COOKIE_DOMAIN = None  # Use current domain
CSRF_FAILURE_VIEW = 'users.views.csrf_failure_view'
CSRF_USE_SESSIONS = False  # Use cookies for CSRF tokens
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://code-alpha-aetheria.onrender.com",
    "https://socialmedia-phi-roan.vercel.app",
]
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS")
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS += csrf_origins_env.split(",")

# Frame Clickjacking Protection
X_FRAME_OPTIONS = "DENY"

# Content Type & MIME Sniffing Protection
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy
REFERRER_POLICY = "strict-origin-when-cross-origin"

# Security Headers (Production)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True").strip().lower() in {"true", "1", "yes"}
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security Policy (CSP) - Prevent XSS
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
        "script-src": ("'self'", "https://cdn.jsdelivr.net", "https://www.gstatic.com"),
        "style-src": ("'self'", "'unsafe-inline'", "https://cdnjs.cloudflare.com", "https://fonts.googleapis.com"),
        "font-src": ("'self'", "https://fonts.gstatic.com"),
        "img-src": ("'self'", "data:", "https:"),
        "media-src": ("'self'",),
        "connect-src": ("'self'", "https:"),
        "frame-ancestors": ("'none'",),
        "form-action": ("'self'",),
    }
    
    # Permissions Policy (Feature-Policy)
    SECURE_PERMISSIONS_POLICY = {
        "accelerometer": [],
        "camera": [],
        "geolocation": [],
        "microphone": [],
        "payment": [],
        "usb": [],
    }

# ──────────────────────────────────────────────
# AUTHENTICATION & AUTHORIZATION
# ──────────────────────────────────────────────

# Rate Limiting - API & Authentication
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = '5/m'  # 5 requests per minute per IP
RATELIMIT_BLOCK = False

# Password Security
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8}
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Account Lockout After Failed Attempts
AUTH_FAILURE_LIMIT = 5
AUTH_FAILURE_TIMEOUT = 1800  # 30 minutes

# ──────────────────────────────────────────────
# WEBSOCKET SECURITY
# ──────────────────────────────────────────────

WEBSOCKET_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]
ws_origins_env = os.environ.get("WEBSOCKET_ALLOWED_ORIGINS")
if ws_origins_env:
    WEBSOCKET_ALLOWED_ORIGINS += ws_origins_env.split(",")

# WebSocket Connection Timeouts
WS_HEARTBEAT_INTERVAL = 30  # seconds
WS_HEARTBEAT_TIMEOUT = 60  # seconds
WS_MAX_CONNECTIONS_PER_USER = 5

# ──────────────────────────────────────────────
# FILE UPLOAD SECURITY
# ──────────────────────────────────────────────

# Allowed file extensions for uploads
ALLOWED_UPLOAD_EXTENSIONS = [
    'jpg', 'jpeg', 'png', 'gif', 'webp',  # Images
    'mp4', 'webm', 'mov', 'avi',  # Videos
    'pdf', 'doc', 'docx', 'txt',  # Documents
]

# File size limits
MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50MB
MAX_IMAGE_SIZE = 10 * 1024 * 1024  # 10MB
MAX_VIDEO_SIZE = 100 * 1024 * 1024  # 100MB

# Quarantine suspicious uploads
FILE_QUARANTINE_DIR = BASE_DIR / 'quarantine'
FILE_QUARANTINE_DIR.mkdir(exist_ok=True)

# ──────────────────────────────────────────────
# CORS & TRUSTED ORIGINS
# ──────────────────────────────────────────────

# Restrict CORS to specific origins (not wildcard)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]
cors_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS")
if cors_origins_env:
    CORS_ALLOWED_ORIGINS += cors_origins_env.split(",")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ──────────────────────────────────────────────
# CACHING CONFIGURATION (PERFORMANCE)
# ──────────────────────────────────────────────

# Try to use Redis, fall back to in-memory cache if not available
if REDIS_URL:
    try:
        import django_redis
        # Use Redis for caching (production)
        CACHES = {
            "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": REDIS_URL,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "SOCKET_CONNECT_TIMEOUT": 5,
                    "SOCKET_TIMEOUT": 5,
                    "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                    "IGNORE_EXCEPTIONS": True,
                    "CONNECTION_POOL_KWARGS": {"max_connections": 50, "retry_on_timeout": True},
                },
                "KEY_PREFIX": "aetheria",
                "TIMEOUT": 300,  # 5 minutes default
            }
        }
        # Use Redis for sessions (production)
        SESSION_ENGINE = "django.contrib.sessions.backends.cache"
        SESSION_CACHE_ALIAS = "default"
        print("Redis caching enabled")
    except ImportError:
        print("WARNING: django-redis not installed. Using in-memory cache.")
        # Fall back to in-memory cache
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "unique-aetheria-cache",
                "OPTIONS": {
                    "MAX_ENTRIES": 1000,
                }
            }
        }
        SESSION_ENGINE = "django.contrib.sessions.backends.db"
else:
    # Use in-memory cache (development/no Redis)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-aetheria-cache",
            "OPTIONS": {
                "MAX_ENTRIES": 1000,
            }
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = "default"
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = "aetheria"

# ──────────────────────────────────────────────
# DATABASE OPTIMIZATION & QUERY SETTINGS
# ──────────────────────────────────────────────

# Enable persistent connections
DATABASES["default"]["CONN_MAX_AGE"] = 600

# Atomic requests for data integrity
if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"]["ATOMIC_REQUESTS"] = False
    DATABASES["default"]["AUTOCOMMIT"] = True
    
    # PostgreSQL-specific optimizations
    opts = DATABASES["default"].setdefault("OPTIONS", {})
    opts.setdefault("connect_timeout", 10)
    opts.setdefault("sslmode", "require" if not DEBUG else "prefer")

# ──────────────────────────────────────────────
# DATABASE CONNECTION POOLING
# ──────────────────────────────────────────────

# For PostgreSQL with psycopg2-pool (optional, requires: pip install psycopg[binary])
# Uncomment to enable connection pooling
# if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
#     import psycopg
#     from psycopg_pool import ConnectionPool
#     DATABASES["default"]["OPTIONS"]["connection_factory"] = psycopg.pool.ConnectionPool

# ──────────────────────────────────────────────
# Firebase Admin SDK Initialization
# ──────────────────────────────────────────────
import firebase_admin
from firebase_admin import credentials
import json

FIREBASE_KEY_PATH = os.path.join(BASE_DIR, 'firebase-service-account.json')
if not firebase_admin._apps:
    cred = None
    if os.environ.get("FIREBASE_CREDENTIALS_JSON"):
        cred_dict = json.loads(os.environ.get("FIREBASE_CREDENTIALS_JSON"))
        cred = credentials.Certificate(cred_dict)
    elif os.path.exists(FIREBASE_KEY_PATH):
        cred = credentials.Certificate(FIREBASE_KEY_PATH)
        
    if cred:
        firebase_admin.initialize_app(cred)


# ──────────────────────────────────────────────
# LOGGING CONFIGURATION FOR PRODUCTION
# ──────────────────────────────────────────────

import logging.config
from datetime import datetime

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'aetheria.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'aetheria_errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'websocket_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'websocket.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'firebase_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'firebase.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'notification_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'notifications.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'channels': {
            'handlers': ['websocket_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.consumers': {
            'handlers': ['websocket_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.utils': {
            'handlers': ['firebase_file', 'notification_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'firebase_admin': {
            'handlers': ['firebase_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'aetheria': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        }
    },
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    }
}

# Apply logging configuration
logging.config.dictConfig(LOGGING)

# Email Configuration
if DEBUG and not os.environ.get('EMAIL_HOST_USER'):
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@aetheria.com')

# ──────────────────────────────────────────────
# PRODUCTION OPTIMIZATION SETTINGS
# ──────────────────────────────────────────────

# Middleware optimization - Enable GZip compression
if not DEBUG:
    try:
        if 'django.middleware.gzip.GZipMiddleware' not in MIDDLEWARE:
            MIDDLEWARE.insert(0, 'django.middleware.gzip.GZipMiddleware')
    except Exception as e:
        print(f"Could not add GZip middleware: {e}")

# Enable database connection persistence
try:
    CONN_MAX_AGE = 600
    DATABASES['default']['CONN_MAX_AGE'] = 600
except Exception as e:
    print(f"Could not set connection max age: {e}")

# Query optimization - Select related & prefetch
DATABASE_QUERY_TIMEOUT = 30  # seconds

# Cache versioning for automatic cache busting on deployments
CACHE_VERSION = 1
VERSION = os.environ.get('VERSION', '1.0.0')

# Optimize template loading (use cached loader in production)
if not DEBUG:
    try:
        for template_engine in TEMPLATES:
            if template_engine.get('BACKEND') == 'django.template.backends.django.DjangoTemplates':
                # Ensure OPTIONS exists
                if 'OPTIONS' not in template_engine:
                    template_engine['OPTIONS'] = {}

                # When setting explicit loaders, Django requires `APP_DIRS` to be False.
                # If `APP_DIRS` is present and True, disable it to avoid ImproperlyConfigured.
                if template_engine.get('APP_DIRS'):
                    template_engine['APP_DIRS'] = False

                template_engine['OPTIONS']['loaders'] = [
                    ('django.template.loaders.cached.Loader', [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ]),
                ]
    except Exception as e:
        print(f"Could not optimize template loading: {e}")

# Database query timeout.
try:
    if DATABASES.get('default', {}).get('ENGINE') == 'django.db.backends.postgresql':
        DATABASES['default'].setdefault('OPTIONS', {})
        if database_uses_neon_pooler(DATABASES['default']):
            DATABASES['default']['OPTIONS'].pop('options', None)
            DISABLE_SERVER_SIDE_CURSORS = True
        else:
            existing_options = DATABASES['default']['OPTIONS'].get('options', '')
            timeout_option = f"-c statement_timeout={DATABASE_QUERY_TIMEOUT * 1000}"
            DATABASES['default']['OPTIONS']['options'] = (
                f"{existing_options} {timeout_option}".strip()
                if timeout_option not in existing_options
                else existing_options
            )
except Exception as e:
    print(f"Could not set database statement timeout: {e}")

# Request timeout settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Pagination defaults
PAGINATION_SIZE = 20

# API Rate Limiting
RATELIMIT_ENABLE = not DEBUG
RATELIMIT_VIEW_RATE = '1000/h'  # 1000 requests per hour per IP
RATELIMIT_BLOCK = True

# Print production configuration status
import sys
try:
    # Only print debug info if not in a CI/build environment
    is_build_env = os.environ.get('CI') or os.environ.get('RENDER') or os.environ.get('VERCEL')
    if is_build_env is None or DEBUG:
        print("\nProduction optimizations loaded", file=sys.stderr)
        print(f"CSRF_COOKIE_HTTPONLY: {CSRF_COOKIE_HTTPONLY}", file=sys.stderr)
        print(f"CSRF_COOKIE_SECURE: {CSRF_COOKIE_SECURE}", file=sys.stderr)
        print(f"CSRF_COOKIE_SAMESITE: {CSRF_COOKIE_SAMESITE}", file=sys.stderr)
        print(f"DEBUG: {DEBUG}", file=sys.stderr)
        print(f"Database: {DATABASES.get('default', {}).get('NAME', 'unknown')}", file=sys.stderr)
        print(file=sys.stderr)
except Exception as e:
    print(f"Error printing configuration: {e}", file=sys.stderr)
