"""
Django settings for socialmedia project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-x4n5uj&qkfkw-=&_n0lx6u-yz1a8f_^$mhaz($vn5-55$9st4s")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [host.strip() for host in os.environ.get("ALLOWED_HOSTS", "*").split(",") if host.strip()]

if not DEBUG:
    if SECRET_KEY.startswith("django-insecure-"):
        raise ImproperlyConfigured("Set a strong SECRET_KEY when DEBUG=False.")
    if "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured("Set explicit ALLOWED_HOSTS when DEBUG=False.")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom Apps
    "users.apps.UsersConfig",
    "posts.apps.PostsConfig",
]

# Cloudinary Integration for Production Media
if os.environ.get("CLOUDINARY_URL"):
    INSTALLED_APPS.append("cloudinary")
    INSTALLED_APPS.append("cloudinary_storage")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # Production Static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "users.middleware.EmailVerificationMiddleware",
    "users.middleware.APIRateLimitMiddleware",
]

ROOT_URLCONF = "socialmedia.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.global_sidebar_context",
            ],
        },
    },
]

WSGI_APPLICATION = "socialmedia.wsgi.application"
ASGI_APPLICATION = "socialmedia.asgi.application"

# Django Channels Configuration
REDIS_URL = os.environ.get("REDIS_URL")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [{
                    "address": REDIS_URL,
                    "health_check_interval": 20,
                    "socket_keepalive": True,
                    "socket_timeout": 20,
                    "socket_connect_timeout": 5,
                    "retry_on_timeout": True,
                }],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import shutil

VERCEL_ENV = os.environ.get("VERCEL") == "1"
DB_PATH = BASE_DIR / "db.sqlite3"

if VERCEL_ENV:
    # Copy SQLite DB to writable /tmp directory if on Vercel
    tmp_db_path = "/tmp/db.sqlite3"
    if not os.path.exists(tmp_db_path) and os.path.exists(DB_PATH):
        shutil.copy2(DB_PATH, tmp_db_path)
    DB_PATH = tmp_db_path

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_PATH,
    }
}

# PostgreSQL Database Configuration for production
if os.environ.get("DATABASE_URL"):
    DATABASES["default"] = dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=False,  # Set to True only on production with SSL
    )
    # PostgreSQL-specific connection settings
    DATABASES["default"]["OPTIONS"] = {
        "connect_timeout": 10,
    }
elif os.environ.get("POSTGRES_PASSWORD"):
    # Local development PostgreSQL
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "aetheria"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "connect_timeout": 10,
        }
    }

# MongoDB Configuration (via Djongo) if MONGO_URL is provided
if os.environ.get("MONGO_URL"):
    DATABASES = {
        "default": {
            "ENGINE": "djongo",
            "NAME": "aetheria_db",
            "ENFORCE_SCHEMA": False,
            "CLIENT": {
                "host": os.environ.get("MONGO_URL"),
            }
        }
    }

if not DEBUG and DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    raise ImproperlyConfigured("Production requires DATABASE_URL or PostgreSQL settings; SQLite is disabled when DEBUG=False.")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Static files storage settings for WhiteNoise caching/compression (modern Django 4.2+)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Backward compatibility for django-cloudinary-storage which crashes without this in Django 4.2+
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Media Files (User uploads)
MEDIA_URL = "/media/"

if os.environ.get("CLOUDINARY_URL"):
    STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"
    MEDIA_ROOT = BASE_DIR / "media"
elif VERCEL_ENV:
    MEDIA_ROOT = "/tmp/media"
    import os
    os.makedirs(MEDIA_ROOT, exist_ok=True)
else:
    MEDIA_ROOT = BASE_DIR / "media"

# Authentication Redirects
LOGIN_REDIRECT_URL = "feed"
LOGOUT_REDIRECT_URL = "landing"
LOGIN_URL = "login"

# CSRF Trusted Origins for Deployment
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://*.vercel.app",
]
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS")
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS += csrf_origins_env.split(",")

# ──────────────────────────────────────────────
# ENHANCED SECURITY HEADERS & POLICIES
# ──────────────────────────────────────────────

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF Protection
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_FAILURE_VIEW = 'users.views.csrf_failure_view'

# Frame Clickjacking Protection
X_FRAME_OPTIONS = "DENY"

# Content Type & MIME Sniffing Protection
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# Referrer Policy
REFERRER_POLICY = "strict-origin-when-cross-origin"

# Security Headers (Production)
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True") == "True"
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security Policy (CSP) - Prevent XSS
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
        "script-src": ("'self'", "https://cdn.jsdelivr.net", "https://www.gstatic.com"),
        "style-src": ("'self'", "'unsafe-inline'", "https://cdnjs.cloudflare.com", "https://fonts.googleapis.com"),
        "font-src": ("'self'", "https://fonts.gstatic.com"),
        "img-src": ("'self'", "data:", "https:"),
        "media-src": ("'self'",),
        "connect-src": ("'self'", "https:"),
        "frame-ancestors": ("'none'",),
        "form-action": ("'self'",),
    }
    
    # Permissions Policy (Feature-Policy)
    SECURE_PERMISSIONS_POLICY = {
        "accelerometer": [],
        "camera": [],
        "geolocation": [],
        "microphone": [],
        "payment": [],
        "usb": [],
    }

# ──────────────────────────────────────────────
# AUTHENTICATION & AUTHORIZATION
# ──────────────────────────────────────────────

# Rate Limiting - API & Authentication
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = '5/m'  # 5 requests per minute per IP
RATELIMIT_BLOCK = False

# Password Security
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12}
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Account Lockout After Failed Attempts
AUTH_FAILURE_LIMIT = 5
AUTH_FAILURE_TIMEOUT = 1800  # 30 minutes

# ──────────────────────────────────────────────
# WEBSOCKET SECURITY
# ──────────────────────────────────────────────

WEBSOCKET_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]
ws_origins_env = os.environ.get("WEBSOCKET_ALLOWED_ORIGINS")
if ws_origins_env:
    WEBSOCKET_ALLOWED_ORIGINS += ws_origins_env.split(",")

# WebSocket Connection Timeouts
WS_HEARTBEAT_INTERVAL = 30  # seconds
WS_HEARTBEAT_TIMEOUT = 60  # seconds
WS_MAX_CONNECTIONS_PER_USER = 5

# ──────────────────────────────────────────────
# FILE UPLOAD SECURITY
# ──────────────────────────────────────────────

# Allowed file extensions for uploads
ALLOWED_UPLOAD_EXTENSIONS = [
    'jpg', 'jpeg', 'png', 'gif', 'webp',  # Images
    'mp4', 'webm', 'mov', 'avi',  # Videos
    'pdf', 'doc', 'docx', 'txt',  # Documents
]

# File size limits
MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50MB
MAX_IMAGE_SIZE = 10 * 1024 * 1024  # 10MB
MAX_VIDEO_SIZE = 100 * 1024 * 1024  # 100MB

# Quarantine suspicious uploads
FILE_QUARANTINE_DIR = BASE_DIR / 'quarantine'
FILE_QUARANTINE_DIR.mkdir(exist_ok=True)

# ──────────────────────────────────────────────
# CORS & TRUSTED ORIGINS
# ──────────────────────────────────────────────

# Restrict CORS to specific origins (not wildcard)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]
cors_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS")
if cors_origins_env:
    CORS_ALLOWED_ORIGINS += cors_origins_env.split(",")

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://*.vercel.app",
    "http://localhost:*",
]
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS")
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS += csrf_origins_env.split(",")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ──────────────────────────────────────────────
# CACHING CONFIGURATION (PERFORMANCE)
# ──────────────────────────────────────────────

if REDIS_URL:
    # Use Redis for caching (production)
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "IGNORE_EXCEPTIONS": True,
                "CONNECTION_POOL_KWARGS": {"max_connections": 50, "retry_on_timeout": True},
            },
            "KEY_PREFIX": "aetheria",
            "TIMEOUT": 300,  # 5 minutes default
        }
    }
    
    # Use Redis for sessions (production)
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
else:
    # Use in-memory cache (development)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-aetheria-cache",
            "OPTIONS": {
                "MAX_ENTRIES": 1000,
            }
        }
    }

# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = "default"
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = "aetheria"

# ──────────────────────────────────────────────
# DATABASE OPTIMIZATION & QUERY SETTINGS
# ──────────────────────────────────────────────

# Enable persistent connections
DATABASES["default"]["CONN_MAX_AGE"] = 600

# Atomic requests for data integrity
if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"]["ATOMIC_REQUESTS"] = False
    DATABASES["default"]["AUTOCOMMIT"] = True
    
    # PostgreSQL-specific optimizations
    DATABASES["default"]["OPTIONS"] = {
        "connect_timeout": 10,
        "options": "-c default_transaction_isolation=read_committed",
        "sslmode": "require" if not DEBUG else "prefer",
    }

# ──────────────────────────────────────────────
# DATABASE CONNECTION POOLING
# ──────────────────────────────────────────────

# For PostgreSQL with psycopg2-pool (optional, requires: pip install psycopg[binary])
# Uncomment to enable connection pooling
# if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
#     import psycopg
#     from psycopg_pool import ConnectionPool
#     DATABASES["default"]["OPTIONS"]["connection_factory"] = psycopg.pool.ConnectionPool

# ──────────────────────────────────────────────
# Firebase Admin SDK Initialization
# ──────────────────────────────────────────────
import firebase_admin
from firebase_admin import credentials
import json

FIREBASE_KEY_PATH = os.path.join(BASE_DIR, 'firebase-service-account.json')
if not firebase_admin._apps:
    cred = None
    if os.environ.get("FIREBASE_CREDENTIALS_JSON"):
        cred_dict = json.loads(os.environ.get("FIREBASE_CREDENTIALS_JSON"))
        cred = credentials.Certificate(cred_dict)
    elif os.path.exists(FIREBASE_KEY_PATH):
        cred = credentials.Certificate(FIREBASE_KEY_PATH)
        
    if cred:
        firebase_admin.initialize_app(cred)


# ──────────────────────────────────────────────
# LOGGING CONFIGURATION FOR PRODUCTION
# ──────────────────────────────────────────────

import logging.config
from datetime import datetime

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'aetheria.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'aetheria_errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'websocket_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'websocket.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'firebase_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'firebase.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'notification_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'notifications.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'channels': {
            'handlers': ['websocket_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.consumers': {
            'handlers': ['websocket_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.utils': {
            'handlers': ['firebase_file', 'notification_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'firebase_admin': {
            'handlers': ['firebase_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'aetheria': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        }
    },
    'root': {
        'handlers': ['console', 'file', 'error_file'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    }
}

# Apply logging configuration
logging.config.dictConfig(LOGGING)
