# Generated by Django 6.0.6 on 2026-06-06 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_message_is_pinned_calllog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="users_messa_created_67ebe9_idx"
            ),
        ),
    ]
