# Generated by Django 6.0.6 on 2026-06-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_message_users_messa_created_67ebe9_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitypost",
            name="community",
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="author",
        ),
        migrations.RemoveField(
            model_name="premiumuser",
            name="user",
        ),
        migrations.DeleteModel(
            name="Community",
        ),
        migrations.DeleteModel(
            name="CommunityPost",
        ),
        migrations.DeleteModel(
            name="PremiumUser",
        ),
    ]
