# Generated by Django 6.0.6 on 2026-06-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_communitypost_community_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("follow_request", "Follow Request"),
                    ("follow_accept", "Follow Accept"),
                    ("message", "Message"),
                    ("mention", "Mention"),
                    ("story_reaction", "Story Reaction"),
                ],
                max_length=20,
            ),
        ),
    ]
