# Generated by Django 6.0.6 on 2026-06-08 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment_posts_comme_created_f825cb_idx_and_more"),
        ("users", "0011_alter_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "created_at"], name="users_devic_user_id_7429d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "created_at"], name="users_follo_followe_229ec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["following", "created_at"],
                name="users_follo_followi_dcf251_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="followrequest",
            index=models.Index(
                fields=["receiver", "created_at"], name="users_follo_receive_914d2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="followrequest",
            index=models.Index(
                fields=["sender", "created_at"], name="users_follo_sender__00e100_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["user", "is_archived", "is_pinned"],
                name="users_group_user_id_9f9b85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["chat_room", "user"], name="users_group_chat_ro_6dc7b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["receiver", "status", "created_at"],
                name="users_messa_receive_6072d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat_room", "created_at"],
                name="users_messa_chat_ro_2b4eda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="users_messa_sender__313a92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "created_at"], name="users_messa_message_fd5133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["receiver", "is_read", "created_at"],
                name="users_notif_receive_982104_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["sender", "created_at"], name="users_notif_sender__d17c82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["author", "expires_at"], name="users_story_author__cbaf18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["expires_at"], name="users_story_expires_1e6f97_idx"
            ),
        ),
    ]
