# Generated by Django 6.0.6 on 2026-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_devicetoken_users_devic_user_id_7429d4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
