# Generated by Django 6.0.6 on 2026-06-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_community_communitypost_premiumuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PremiumUser",
        ),
    ]
